/* tslint:disable */
/* eslint-disable */
/**
 * PAM
 * Documentação e testes interativos dos endpoints de Simulação, Turbinas e Catálogo
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CreateSimulationDto
 */
export interface CreateSimulationDto {
    /**
     * Nome da simulacao
     * @type {string}
     * @memberof CreateSimulationDto
     */
    'name': string;
    /**
     * id das turbinas
     * @type {Array<number>}
     * @memberof CreateSimulationDto
     */
    'turbine_ids': Array<number>;
}
/**
 * 
 * @export
 * @interface CreateTurbineCatalogDto
 */
export interface CreateTurbineCatalogDto {
    /**
     * Nome do modelo de turbina
     * @type {string}
     * @memberof CreateTurbineCatalogDto
     */
    'name': string;
    /**
     * Potencia do modelo de turbina
     * @type {number}
     * @memberof CreateTurbineCatalogDto
     */
    'nominal_power': number;
    /**
     * Diâmetro do rotor do modelo de turbina
     * @type {number}
     * @memberof CreateTurbineCatalogDto
     */
    'rotor_diameter': number;
    /**
     * Fabricante do modelo de turbina
     * @type {string}
     * @memberof CreateTurbineCatalogDto
     */
    'manufacturer': string;
}
/**
 * 
 * @export
 * @interface CreateTurbineDto
 */
export interface CreateTurbineDto {
    /**
     * Nome da turbina
     * @type {string}
     * @memberof CreateTurbineDto
     */
    'name': string;
    /**
     * Localização no formato GeoJSON
     * @type {PointCoordinatesDto}
     * @memberof CreateTurbineDto
     */
    'coordinates': PointCoordinatesDto;
    /**
     * ID da simulacão a qual a turbina pertence
     * @type {number}
     * @memberof CreateTurbineDto
     */
    'simulation_id'?: number | null;
    /**
     * ID do catálogo de turbina ao qual a turbina pertence
     * @type {number}
     * @memberof CreateTurbineDto
     */
    'turbine_catalog_id': number;
}
/**
 * 
 * @export
 * @interface PointCoordinatesDto
 */
export interface PointCoordinatesDto {
    /**
     * 
     * @type {string}
     * @memberof PointCoordinatesDto
     */
    'type': PointCoordinatesDtoTypeEnum;
    /**
     * Array com [longitude, latitude]
     * @type {Array<number>}
     * @memberof PointCoordinatesDto
     */
    'coordinates': Array<number>;
}

export const PointCoordinatesDtoTypeEnum = {
    Point: 'Point'
} as const;

export type PointCoordinatesDtoTypeEnum = typeof PointCoordinatesDtoTypeEnum[keyof typeof PointCoordinatesDtoTypeEnum];

/**
 * 
 * @export
 * @interface ResponseSimulationDto
 */
export interface ResponseSimulationDto {
    /**
     * 
     * @type {number}
     * @memberof ResponseSimulationDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ResponseSimulationDto
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface ResponseTurbineCatalogDto
 */
export interface ResponseTurbineCatalogDto {
    /**
     * Nome do modelo de turbina
     * @type {string}
     * @memberof ResponseTurbineCatalogDto
     */
    'name': string;
    /**
     * Potencia do modelo de turbina
     * @type {number}
     * @memberof ResponseTurbineCatalogDto
     */
    'nominal_power': number;
    /**
     * Diâmetro do rotor do modelo de turbina
     * @type {number}
     * @memberof ResponseTurbineCatalogDto
     */
    'rotor_diameter': number;
    /**
     * Fabricante do modelo de turbina
     * @type {string}
     * @memberof ResponseTurbineCatalogDto
     */
    'manufacturer': string;
    /**
     * 
     * @type {number}
     * @memberof ResponseTurbineCatalogDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ResponseTurbineCatalogDto
     */
    'created_at': string;
}
/**
 * 
 * @export
 * @interface ResponseTurbineDto
 */
export interface ResponseTurbineDto {
    /**
     * 
     * @type {number}
     * @memberof ResponseTurbineDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ResponseTurbineDto
     */
    'name': string;
    /**
     * 
     * @type {PointCoordinatesDto}
     * @memberof ResponseTurbineDto
     */
    'coordinates': PointCoordinatesDto;
    /**
     * 
     * @type {number}
     * @memberof ResponseTurbineDto
     */
    'turbine_catalog_id': number;
    /**
     * 
     * @type {number}
     * @memberof ResponseTurbineDto
     */
    'simulation_id': number | null;
}
/**
 * 
 * @export
 * @interface TurbinesControllerRemove200Response
 */
export interface TurbinesControllerRemove200Response {
    /**
     * 
     * @type {string}
     * @memberof TurbinesControllerRemove200Response
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface UpdateSimulationDto
 */
export interface UpdateSimulationDto {
    /**
     * Nome da simulacao
     * @type {string}
     * @memberof UpdateSimulationDto
     */
    'name'?: string;
    /**
     * id das turbinas
     * @type {Array<number>}
     * @memberof UpdateSimulationDto
     */
    'turbine_ids'?: Array<number>;
}
/**
 * 
 * @export
 * @interface UpdateTurbineCatalogDto
 */
export interface UpdateTurbineCatalogDto {
    /**
     * Nome do modelo de turbina
     * @type {string}
     * @memberof UpdateTurbineCatalogDto
     */
    'name'?: string;
    /**
     * Potencia do modelo de turbina
     * @type {number}
     * @memberof UpdateTurbineCatalogDto
     */
    'nominal_power'?: number;
    /**
     * Diâmetro do rotor do modelo de turbina
     * @type {number}
     * @memberof UpdateTurbineCatalogDto
     */
    'rotor_diameter'?: number;
    /**
     * Fabricante do modelo de turbina
     * @type {string}
     * @memberof UpdateTurbineCatalogDto
     */
    'manufacturer'?: string;
}
/**
 * 
 * @export
 * @interface UpdateTurbineDto
 */
export interface UpdateTurbineDto {
    /**
     * Nome da turbina
     * @type {string}
     * @memberof UpdateTurbineDto
     */
    'name'?: string;
    /**
     * Localização no formato GeoJSON
     * @type {PointCoordinatesDto}
     * @memberof UpdateTurbineDto
     */
    'coordinates'?: PointCoordinatesDto;
    /**
     * ID do catálogo de turbina ao qual a turbina pertence
     * @type {number}
     * @memberof UpdateTurbineDto
     */
    'turbine_catalog_id'?: number;
}

/**
 * AppApi - axios parameter creator
 * @export
 */
export const AppApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppApi - functional programming interface
 * @export
 */
export const AppApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerGetHello(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerGetHello(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.appControllerGetHello']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppApi - factory interface
 * @export
 */
export const AppApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello(options?: any): AxiosPromise<void> {
            return localVarFp.appControllerGetHello(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppApi - interface
 * @export
 * @interface AppApi
 */
export interface AppApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApiInterface
     */
    appControllerGetHello(options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * AppApi - object-oriented interface
 * @export
 * @class AppApi
 * @extends {BaseAPI}
 */
export class AppApi extends BaseAPI implements AppApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public appControllerGetHello(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).appControllerGetHello(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SimulationApi - axios parameter creator
 * @export
 */
export const SimulationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateSimulationDto} createSimulationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulationControllerCreate: async (createSimulationDto: CreateSimulationDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSimulationDto' is not null or undefined
            assertParamExists('simulationControllerCreate', 'createSimulationDto', createSimulationDto)
            const localVarPath = `/simulation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSimulationDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulationControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/simulation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulationControllerFindOne: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('simulationControllerFindOne', 'id', id)
            const localVarPath = `/simulation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulationControllerRemove: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('simulationControllerRemove', 'id', id)
            const localVarPath = `/simulation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {UpdateSimulationDto} updateSimulationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulationControllerUpdate: async (id: number, updateSimulationDto: UpdateSimulationDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('simulationControllerUpdate', 'id', id)
            // verify required parameter 'updateSimulationDto' is not null or undefined
            assertParamExists('simulationControllerUpdate', 'updateSimulationDto', updateSimulationDto)
            const localVarPath = `/simulation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSimulationDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SimulationApi - functional programming interface
 * @export
 */
export const SimulationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SimulationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateSimulationDto} createSimulationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async simulationControllerCreate(createSimulationDto: CreateSimulationDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseSimulationDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.simulationControllerCreate(createSimulationDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SimulationApi.simulationControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async simulationControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ResponseSimulationDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.simulationControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SimulationApi.simulationControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async simulationControllerFindOne(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseSimulationDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.simulationControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SimulationApi.simulationControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async simulationControllerRemove(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TurbinesControllerRemove200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.simulationControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SimulationApi.simulationControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {UpdateSimulationDto} updateSimulationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async simulationControllerUpdate(id: number, updateSimulationDto: UpdateSimulationDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseSimulationDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.simulationControllerUpdate(id, updateSimulationDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SimulationApi.simulationControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SimulationApi - factory interface
 * @export
 */
export const SimulationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SimulationApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateSimulationDto} createSimulationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulationControllerCreate(createSimulationDto: CreateSimulationDto, options?: any): AxiosPromise<ResponseSimulationDto> {
            return localVarFp.simulationControllerCreate(createSimulationDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulationControllerFindAll(options?: any): AxiosPromise<Array<ResponseSimulationDto>> {
            return localVarFp.simulationControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulationControllerFindOne(id: number, options?: any): AxiosPromise<ResponseSimulationDto> {
            return localVarFp.simulationControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulationControllerRemove(id: number, options?: any): AxiosPromise<TurbinesControllerRemove200Response> {
            return localVarFp.simulationControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {UpdateSimulationDto} updateSimulationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulationControllerUpdate(id: number, updateSimulationDto: UpdateSimulationDto, options?: any): AxiosPromise<ResponseSimulationDto> {
            return localVarFp.simulationControllerUpdate(id, updateSimulationDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SimulationApi - interface
 * @export
 * @interface SimulationApi
 */
export interface SimulationApiInterface {
    /**
     * 
     * @param {CreateSimulationDto} createSimulationDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimulationApiInterface
     */
    simulationControllerCreate(createSimulationDto: CreateSimulationDto, options?: RawAxiosRequestConfig): AxiosPromise<ResponseSimulationDto>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimulationApiInterface
     */
    simulationControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<ResponseSimulationDto>>;

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimulationApiInterface
     */
    simulationControllerFindOne(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseSimulationDto>;

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimulationApiInterface
     */
    simulationControllerRemove(id: number, options?: RawAxiosRequestConfig): AxiosPromise<TurbinesControllerRemove200Response>;

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {UpdateSimulationDto} updateSimulationDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimulationApiInterface
     */
    simulationControllerUpdate(id: number, updateSimulationDto: UpdateSimulationDto, options?: RawAxiosRequestConfig): AxiosPromise<ResponseSimulationDto>;

}

/**
 * SimulationApi - object-oriented interface
 * @export
 * @class SimulationApi
 * @extends {BaseAPI}
 */
export class SimulationApi extends BaseAPI implements SimulationApiInterface {
    /**
     * 
     * @param {CreateSimulationDto} createSimulationDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimulationApi
     */
    public simulationControllerCreate(createSimulationDto: CreateSimulationDto, options?: RawAxiosRequestConfig) {
        return SimulationApiFp(this.configuration).simulationControllerCreate(createSimulationDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimulationApi
     */
    public simulationControllerFindAll(options?: RawAxiosRequestConfig) {
        return SimulationApiFp(this.configuration).simulationControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimulationApi
     */
    public simulationControllerFindOne(id: number, options?: RawAxiosRequestConfig) {
        return SimulationApiFp(this.configuration).simulationControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimulationApi
     */
    public simulationControllerRemove(id: number, options?: RawAxiosRequestConfig) {
        return SimulationApiFp(this.configuration).simulationControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {UpdateSimulationDto} updateSimulationDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimulationApi
     */
    public simulationControllerUpdate(id: number, updateSimulationDto: UpdateSimulationDto, options?: RawAxiosRequestConfig) {
        return SimulationApiFp(this.configuration).simulationControllerUpdate(id, updateSimulationDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TurbineApi - axios parameter creator
 * @export
 */
export const TurbineApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateTurbineDto} createTurbineDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbinesControllerCreate: async (createTurbineDto: CreateTurbineDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createTurbineDto' is not null or undefined
            assertParamExists('turbinesControllerCreate', 'createTurbineDto', createTurbineDto)
            const localVarPath = `/turbines`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTurbineDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbinesControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/turbines`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbinesControllerFindOne: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('turbinesControllerFindOne', 'id', id)
            const localVarPath = `/turbines/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbinesControllerRemove: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('turbinesControllerRemove', 'id', id)
            const localVarPath = `/turbines/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {UpdateTurbineDto} updateTurbineDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbinesControllerUpdate: async (id: number, updateTurbineDto: UpdateTurbineDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('turbinesControllerUpdate', 'id', id)
            // verify required parameter 'updateTurbineDto' is not null or undefined
            assertParamExists('turbinesControllerUpdate', 'updateTurbineDto', updateTurbineDto)
            const localVarPath = `/turbines/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateTurbineDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TurbineApi - functional programming interface
 * @export
 */
export const TurbineApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TurbineApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateTurbineDto} createTurbineDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async turbinesControllerCreate(createTurbineDto: CreateTurbineDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseTurbineDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.turbinesControllerCreate(createTurbineDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TurbineApi.turbinesControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async turbinesControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ResponseTurbineDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.turbinesControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TurbineApi.turbinesControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async turbinesControllerFindOne(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseTurbineDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.turbinesControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TurbineApi.turbinesControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async turbinesControllerRemove(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TurbinesControllerRemove200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.turbinesControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TurbineApi.turbinesControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {UpdateTurbineDto} updateTurbineDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async turbinesControllerUpdate(id: number, updateTurbineDto: UpdateTurbineDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseTurbineDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.turbinesControllerUpdate(id, updateTurbineDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TurbineApi.turbinesControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TurbineApi - factory interface
 * @export
 */
export const TurbineApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TurbineApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateTurbineDto} createTurbineDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbinesControllerCreate(createTurbineDto: CreateTurbineDto, options?: any): AxiosPromise<ResponseTurbineDto> {
            return localVarFp.turbinesControllerCreate(createTurbineDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbinesControllerFindAll(options?: any): AxiosPromise<Array<ResponseTurbineDto>> {
            return localVarFp.turbinesControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbinesControllerFindOne(id: number, options?: any): AxiosPromise<ResponseTurbineDto> {
            return localVarFp.turbinesControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbinesControllerRemove(id: number, options?: any): AxiosPromise<TurbinesControllerRemove200Response> {
            return localVarFp.turbinesControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {UpdateTurbineDto} updateTurbineDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbinesControllerUpdate(id: number, updateTurbineDto: UpdateTurbineDto, options?: any): AxiosPromise<ResponseTurbineDto> {
            return localVarFp.turbinesControllerUpdate(id, updateTurbineDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TurbineApi - interface
 * @export
 * @interface TurbineApi
 */
export interface TurbineApiInterface {
    /**
     * 
     * @param {CreateTurbineDto} createTurbineDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbineApiInterface
     */
    turbinesControllerCreate(createTurbineDto: CreateTurbineDto, options?: RawAxiosRequestConfig): AxiosPromise<ResponseTurbineDto>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbineApiInterface
     */
    turbinesControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<ResponseTurbineDto>>;

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbineApiInterface
     */
    turbinesControllerFindOne(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseTurbineDto>;

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbineApiInterface
     */
    turbinesControllerRemove(id: number, options?: RawAxiosRequestConfig): AxiosPromise<TurbinesControllerRemove200Response>;

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {UpdateTurbineDto} updateTurbineDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbineApiInterface
     */
    turbinesControllerUpdate(id: number, updateTurbineDto: UpdateTurbineDto, options?: RawAxiosRequestConfig): AxiosPromise<ResponseTurbineDto>;

}

/**
 * TurbineApi - object-oriented interface
 * @export
 * @class TurbineApi
 * @extends {BaseAPI}
 */
export class TurbineApi extends BaseAPI implements TurbineApiInterface {
    /**
     * 
     * @param {CreateTurbineDto} createTurbineDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbineApi
     */
    public turbinesControllerCreate(createTurbineDto: CreateTurbineDto, options?: RawAxiosRequestConfig) {
        return TurbineApiFp(this.configuration).turbinesControllerCreate(createTurbineDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbineApi
     */
    public turbinesControllerFindAll(options?: RawAxiosRequestConfig) {
        return TurbineApiFp(this.configuration).turbinesControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbineApi
     */
    public turbinesControllerFindOne(id: number, options?: RawAxiosRequestConfig) {
        return TurbineApiFp(this.configuration).turbinesControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbineApi
     */
    public turbinesControllerRemove(id: number, options?: RawAxiosRequestConfig) {
        return TurbineApiFp(this.configuration).turbinesControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {UpdateTurbineDto} updateTurbineDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbineApi
     */
    public turbinesControllerUpdate(id: number, updateTurbineDto: UpdateTurbineDto, options?: RawAxiosRequestConfig) {
        return TurbineApiFp(this.configuration).turbinesControllerUpdate(id, updateTurbineDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TurbinesCatalogApi - axios parameter creator
 * @export
 */
export const TurbinesCatalogApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateTurbineCatalogDto} createTurbineCatalogDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbineCatalogControllerCreate: async (createTurbineCatalogDto: CreateTurbineCatalogDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createTurbineCatalogDto' is not null or undefined
            assertParamExists('turbineCatalogControllerCreate', 'createTurbineCatalogDto', createTurbineCatalogDto)
            const localVarPath = `/turbine-catalog`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTurbineCatalogDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbineCatalogControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/turbine-catalog`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbineCatalogControllerFindOne: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('turbineCatalogControllerFindOne', 'id', id)
            const localVarPath = `/turbine-catalog/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbineCatalogControllerRemove: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('turbineCatalogControllerRemove', 'id', id)
            const localVarPath = `/turbine-catalog/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {UpdateTurbineCatalogDto} updateTurbineCatalogDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbineCatalogControllerUpdate: async (id: number, updateTurbineCatalogDto: UpdateTurbineCatalogDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('turbineCatalogControllerUpdate', 'id', id)
            // verify required parameter 'updateTurbineCatalogDto' is not null or undefined
            assertParamExists('turbineCatalogControllerUpdate', 'updateTurbineCatalogDto', updateTurbineCatalogDto)
            const localVarPath = `/turbine-catalog/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateTurbineCatalogDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TurbinesCatalogApi - functional programming interface
 * @export
 */
export const TurbinesCatalogApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TurbinesCatalogApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateTurbineCatalogDto} createTurbineCatalogDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async turbineCatalogControllerCreate(createTurbineCatalogDto: CreateTurbineCatalogDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseTurbineCatalogDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.turbineCatalogControllerCreate(createTurbineCatalogDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TurbinesCatalogApi.turbineCatalogControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async turbineCatalogControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ResponseTurbineCatalogDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.turbineCatalogControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TurbinesCatalogApi.turbineCatalogControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async turbineCatalogControllerFindOne(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseTurbineCatalogDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.turbineCatalogControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TurbinesCatalogApi.turbineCatalogControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async turbineCatalogControllerRemove(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TurbinesControllerRemove200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.turbineCatalogControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TurbinesCatalogApi.turbineCatalogControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {UpdateTurbineCatalogDto} updateTurbineCatalogDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async turbineCatalogControllerUpdate(id: number, updateTurbineCatalogDto: UpdateTurbineCatalogDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseTurbineCatalogDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.turbineCatalogControllerUpdate(id, updateTurbineCatalogDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TurbinesCatalogApi.turbineCatalogControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TurbinesCatalogApi - factory interface
 * @export
 */
export const TurbinesCatalogApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TurbinesCatalogApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateTurbineCatalogDto} createTurbineCatalogDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbineCatalogControllerCreate(createTurbineCatalogDto: CreateTurbineCatalogDto, options?: any): AxiosPromise<ResponseTurbineCatalogDto> {
            return localVarFp.turbineCatalogControllerCreate(createTurbineCatalogDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbineCatalogControllerFindAll(options?: any): AxiosPromise<Array<ResponseTurbineCatalogDto>> {
            return localVarFp.turbineCatalogControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbineCatalogControllerFindOne(id: number, options?: any): AxiosPromise<ResponseTurbineCatalogDto> {
            return localVarFp.turbineCatalogControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbineCatalogControllerRemove(id: number, options?: any): AxiosPromise<TurbinesControllerRemove200Response> {
            return localVarFp.turbineCatalogControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id ID do catalogo
         * @param {UpdateTurbineCatalogDto} updateTurbineCatalogDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        turbineCatalogControllerUpdate(id: number, updateTurbineCatalogDto: UpdateTurbineCatalogDto, options?: any): AxiosPromise<ResponseTurbineCatalogDto> {
            return localVarFp.turbineCatalogControllerUpdate(id, updateTurbineCatalogDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TurbinesCatalogApi - interface
 * @export
 * @interface TurbinesCatalogApi
 */
export interface TurbinesCatalogApiInterface {
    /**
     * 
     * @param {CreateTurbineCatalogDto} createTurbineCatalogDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbinesCatalogApiInterface
     */
    turbineCatalogControllerCreate(createTurbineCatalogDto: CreateTurbineCatalogDto, options?: RawAxiosRequestConfig): AxiosPromise<ResponseTurbineCatalogDto>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbinesCatalogApiInterface
     */
    turbineCatalogControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<ResponseTurbineCatalogDto>>;

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbinesCatalogApiInterface
     */
    turbineCatalogControllerFindOne(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseTurbineCatalogDto>;

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbinesCatalogApiInterface
     */
    turbineCatalogControllerRemove(id: number, options?: RawAxiosRequestConfig): AxiosPromise<TurbinesControllerRemove200Response>;

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {UpdateTurbineCatalogDto} updateTurbineCatalogDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbinesCatalogApiInterface
     */
    turbineCatalogControllerUpdate(id: number, updateTurbineCatalogDto: UpdateTurbineCatalogDto, options?: RawAxiosRequestConfig): AxiosPromise<ResponseTurbineCatalogDto>;

}

/**
 * TurbinesCatalogApi - object-oriented interface
 * @export
 * @class TurbinesCatalogApi
 * @extends {BaseAPI}
 */
export class TurbinesCatalogApi extends BaseAPI implements TurbinesCatalogApiInterface {
    /**
     * 
     * @param {CreateTurbineCatalogDto} createTurbineCatalogDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbinesCatalogApi
     */
    public turbineCatalogControllerCreate(createTurbineCatalogDto: CreateTurbineCatalogDto, options?: RawAxiosRequestConfig) {
        return TurbinesCatalogApiFp(this.configuration).turbineCatalogControllerCreate(createTurbineCatalogDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbinesCatalogApi
     */
    public turbineCatalogControllerFindAll(options?: RawAxiosRequestConfig) {
        return TurbinesCatalogApiFp(this.configuration).turbineCatalogControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbinesCatalogApi
     */
    public turbineCatalogControllerFindOne(id: number, options?: RawAxiosRequestConfig) {
        return TurbinesCatalogApiFp(this.configuration).turbineCatalogControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbinesCatalogApi
     */
    public turbineCatalogControllerRemove(id: number, options?: RawAxiosRequestConfig) {
        return TurbinesCatalogApiFp(this.configuration).turbineCatalogControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id ID do catalogo
     * @param {UpdateTurbineCatalogDto} updateTurbineCatalogDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TurbinesCatalogApi
     */
    public turbineCatalogControllerUpdate(id: number, updateTurbineCatalogDto: UpdateTurbineCatalogDto, options?: RawAxiosRequestConfig) {
        return TurbinesCatalogApiFp(this.configuration).turbineCatalogControllerUpdate(id, updateTurbineCatalogDto, options).then((request) => request(this.axios, this.basePath));
    }
}



